import { getComic, getComics } from "dh-marvel/services/marvel/marvel.service";
import { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Grid from "@mui/material/Grid";
import {
  CardContent,
  Button,
  Card,
  CardActions,
  Typography,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Container,
  Box,
} from "@mui/material";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import React from "react";
import Image from "next/image";

let firstComic = 0;
let quantityComic = 12;
export async function getStaticPaths(): Promise<any> {
  const res = await getComics(firstComic, quantityComic);

  const paths = res.data.results.map((e: any) => ({
    params: {
      id: `${e.id}`,
    },
  }));

  return {
    paths,
    fallback: "blocking",
  };
}

export const getStaticProps: GetStaticProps = async ({ params }) => {
  let tonum = params?.id;
  const comic = await getComic(Number(tonum));
  console.log("comic data " + comic);
  console.log(comic.id, comic.title);

  return {
    props: {
      id: params?.id,
      comicDetail: comic,
    },
    revalidate: 60,
  };
};

type Props = {
  comicDetail: any;
};

const ComicDetails: NextPage<Props> = ({ comicDetail }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container spacing={2}>
        <Container xs="12" alignItems="center" >
          <Typography alingText="Center" variant="h3" color="initial">
            {comicDetail.title}
          </Typography>
        </Container>
        

        <Box xs={12} sm={6}>
          <Image src={comicDetail.thumbnail.path + ".jpg"} width="185px" alt="book cover" height="350px" />
        </Box>
      <Box xs={12} sm={6}>
        <Card  sx={{ minWidth: 275 }}>
          <CardContent>
            <Typography
              sx={{ fontSize: 14 }}
              color="text.secondary"
              gutterBottom
            >
              {comicDetail.title}
            </Typography>
            <Typography sx={{ mb: 1.5 }} color="text.secondary">
              Antes: ${comicDetail.oldPrice}
            </Typography>
            <Typography variant="body2">${comicDetail.oldPrice}</Typography>
          </CardContent>
          <CardActions>
            <Button size="small">COMPRAR</Button>
          </CardActions>
        </Card>
        </Box>
      

     

        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            aria-controls="panel1a-content"
            id="panel1a-header"
          >
            <Typography>Descripcion</Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography>
              {comicDetail.description||"sin descripcion diponible"}
            </Typography>
          </AccordionDetails>
        </Accordion>
      </Grid>
    </>
  );
};

export default ComicDetails;
