import { getComic, getComics } from "dh-marvel/services/marvel/marvel.service";
import { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";

let firstComic = 0;
let quantityComic = 12;

export const getStaticPaths: GetStaticPaths = async () => {
  const res = await getComics(firstComic, quantityComic);

  const paths = res.data.results.map((e: any) => ({
    params: {
      id: `${e.id}`,
    },
  }));
  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  let tonum = params?.id;
  let num = +{ tonum };
  console.log(num);
  const comic = await getComic(num);
  console.log(comic);
  return {
    props: {
      id: params?.id,
      comicDetail: comic,
    },
  };
};

type Props = {
  comicDetail: any;
};

const ComicDetails: NextPage<Props> = ({ comicDetail }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{comicDetail.id}</h1>
    </>
  );
};

export default ComicDetails;
