import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { getComics } from "dh-marvel/services/marvel/marvel.service";
import ComicGrid from "dh-marvel/components/comicGrid.component";
import Grid from "@mui/material/Grid";
import BasicPagination from "dh-marvel/components/pagination.component";
import { Box } from "@mui/material";
import LayoutGeneral from "dh-marvel/components/layouts/layout-general";
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";

interface Props {
  comicsPage: {
    offset: number;
    limit: number;
    total: number;
    count: number;
    results: [];
  };
}

let firstComic = 0;
let quantityComic = 12;

//useEffect

export const getStaticProps: GetStaticProps = async () => {
  const response = await getComics(firstComic, quantityComic);

  return {
    props: {
      comicsPage: response.data,
    },
    revalidate: 60,
  };
};

const Index: NextPage<Props> = ({ comicsPage }) => {
  let pages = Math.round(comicsPage.total / quantityComic);

  return (
    <>
      <Head>
        <title>Marvel Comics store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ flexGrow: 1 }}>
        <Grid container spacing={2}>
          <Grid item xs={12} textAlign="center">
            <h1>Comics {}</h1>
          </Grid>
          <Grid item xs={12} alignContent="center">
            <BasicPagination count={pages} page={1} />
          </Grid>
          <Grid item xs={10} alignItems="center"></Grid>
          <ComicGrid results={comicsPage.results} />
        </Grid>
      </Box>
    </>
  );
};
(Index as any).layout = LayoutGeneral;
export default Index;
